"""add ticket_code to participants

Revision ID: 7060cf053fdf
Revises: 45742fc8d1a7
Create Date: 2026-09-04 18:33:59.999552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7060cf053fdf'
down_revision: Union[str, Sequence[str], None] = '45742fc8d1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_code', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_participants_ticket_code', ['ticket_code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participants_ticket_code', type_='unique')
        batch_op.drop_column('ticket_code')

    # ### end Alembic commands ###
